language: elixir

elixir:
  - 1.1.0
  - 1.2.0

otp_release:
  - 18.0
  - 18.1

env: MIX_ENV=test

sudo: false # faster builds

notifications:
  email: true

script:
  - mix compile
  - mix test
  - mix dogma
